name: Zero Changelog - Release
description: Bump version, update changelog, and create a release.
author: Aaron Klinker

inputs:
  additionalDirs:
    description: See https://jsr.io/@aklinker1/zero-changelog/doc/release/~/ReleaseOptions
  bump:
    description: See https://jsr.io/@aklinker1/zero-changelog/doc/release/~/ReleaseOptions
  commitTemplate:
    description: See https://jsr.io/@aklinker1/zero-changelog/doc/release/~/ReleaseOptions
  dryRun:
    description: See https://jsr.io/@aklinker1/zero-changelog/doc/release/~/ReleaseOptions
  since:
    description: See https://jsr.io/@aklinker1/zero-changelog/doc/release/~/ReleaseOptions
  dryRunPublishCommands:
    description: See https://jsr.io/@aklinker1/zero-changelog/doc/release/~/ReleaseOptions
  path:
    description: See https://jsr.io/@aklinker1/zero-changelog/doc/release/~/ReleaseOptions
  publishCommands:
    description: See https://jsr.io/@aklinker1/zero-changelog/doc/release/~/ReleaseOptions
  releaseArtifacts:
    description: See https://jsr.io/@aklinker1/zero-changelog/doc/release/~/ReleaseOptions
  releaseTitleTemplate:
    description: See https://jsr.io/@aklinker1/zero-changelog/doc/release/~/ReleaseOptions
  tagPrefix:
    description: See https://jsr.io/@aklinker1/zero-changelog/doc/release/~/ReleaseOptions
  versionFiles:
    description: See https://jsr.io/@aklinker1/zero-changelog/doc/release/~/ReleaseOptions
  githubRepo:
    description: See https://jsr.io/@aklinker1/zero-changelog/doc/release/~/ReleaseOptions
  latestRelease:
    description: See https://jsr.io/@aklinker1/zero-changelog/doc/release/~/ReleaseOptions
  throwOnNoChanges:
    description: See https://jsr.io/@aklinker1/zero-changelog/doc/release/~/ReleaseOptions
  githubToken:
    description: See https://jsr.io/@aklinker1/zero-changelog/doc/release/~/ReleaseOptions

outputs:
  version:
    description: The new version that was released.
  tag:
    description: The tag for the new version that was pushed.
  releaseNotes:
    description: The part of the changelog for this version.

runs:
  using: node24
  main: ../dist/release.mjs
