name: Zero Changelog - Summarize Unreleased Commits
description: List commits since the latest release and output a summary
author: Aaron Klinker

inputs:
  paths:
    description: |-
      See
      https://jsr.io/@aklinker1/zero-ioc/doc/summarize-unreleased-commits/~/SummarizeUnreleasedCommitsOptions
  tagPrefixTemplate:
    description: |-
      See
      https://jsr.io/@aklinker1/zero-ioc/doc/summarize-unreleased-commits/~/SummarizeUnreleasedCommitsOptions

outputs:
  text:
    description: Formatted text
  json:
    description: Full json object containing the commits and paths.

runs:
  using: node24
  main: ../dist/summarize-unreleased-commits.mjs
