name: Publish

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run?
        type: boolean
        default: true

jobs:
  validate:
    uses: ./.github/workflows/validate.yml

  release:
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Bump and Release
        uses: ./actions/release
        with:
          publishCommands: |-
            npm publish
            bunx jsr publish
          versionFiles: |-
            package.json
            jsr.json
          dryRun: ${{ inputs.dryRun }}
          dryRunPublishCommands: |-
            npm publish --dry-run
            bunx jsr publish --dry-run --allow-dirty
          githubToken: ${{ secrets.GITHUB_TOKEN }}
